export const COLOR = {
	DARK_GRAY: '#4A4A4A',
	GRAY: '#A9A9A9', // SLIDER GRAY
	LIGHT_GRAY: '#E0E0E0', // FACE GRAY
	ULTRA_LIGHT_GRAY: '#F2F2F2', // FACE GRAY
	DARK_BLUE: '#1F4D75',
	LIGHT_BLUE: '#4AA1D8',
	AQUA: '#55B1C9',
	DARK_GREEN: '#87AD35',
	LIGHT_GREEN: '#94BF3D',
	ORANGE: '#F6BC41',
};

export const MOOD_COLOR = {
	SAD_MAX: COLOR.DARK_GRAY,
	SAD: COLOR.DARK_BLUE,
	SAD_MIN: COLOR.LIGHT_BLUE,
	NEUTRAL: COLOR.AQUA,
	HAPPY_MIN: COLOR.DARK_GREEN,
	HAPPY: COLOR.LIGHT_GREEN,
	HAPPY_MAX: COLOR.ORANGE,
};

export const STYLE = {
	SCREEN_PADDING: 20,
}